spring.application.name=wealth_management



spring.datasource.url=jdbc:postgresql://localhost:5432/wealth_management
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
